name: "Deploy to DigitalOcean"

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout directory
        uses: actions/checkout@v3.3.0
      
      - name: Add private key to ssh agent 
        run: |
          echo ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa
          && eval "$(ssh-agent -s)"  
          && ssh-add ~/.ssh/id_rsa
            
      - name: Add to known hosts
        run: |
          ssh-keyscan -H ${{secrets.DIGITALOCEAN_IP}} > ~/.ssh/known_hosts
        
      - name: Copy code
        run: |
          rsync -avh --delete . \
            ${{ secrets.DIGITALOCEAN_USERNAME}}@${{ secrets.DIGITALOCEAN_IP }}:${{ secrets.DIGITALOCEAN_DEPLOY_PATH }}
