name: "Deploy to DigitalOcean"

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout directory
        uses: actions/checkout@v3.3.0
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{secrets.DIGITALOCEAN_SSH_PRIVATE_KEY}}
        
      - name: Copy code
        run: |
          rsync -avh --delete . ${{secrets.DIGITALOCEAN_USERNAME}}@${{DIGITALOCEAN_IP}}:${{DIGITALOCEAN_DEPLOY_PATH}}
