name: Deploy to DigitalOcean

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout directory
        uses: actions/checkout@v3.3.0
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.5.0
        with:
          key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DIGITALOCEAN_HOST_KEY }}

      - name: Copy code
        run: rsync -avh --delete . \
            ${{ secrets.DIGITALOCEAN_USERNAME}}@${{ secrets.DIGITALOCEAN_IP }}:${{ secrets.DIGITALOCEAN_DEPLOY_PATH }}
