name: Deploy to DigitalOcean

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      
      - name: Set up SSH key
      - uses: webfactory/ssh-agent@v0.3.0
        with:
          ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          
      - name: Deploy to DigitalOcean
        run: |
          rsync -avh --delete . $DIGITALOCEAN_USERNAME@$DIGITALOCEAN_IP:$DIGITALOCEAN_DEPLOY_PATH
